import Head from "next/head";
import { useEffect, useState } from "react";
import Avatar from "../components/Avatar";
import Button from "../components/Buton";
import { loginWithGitHub, onAuthStateChange } from "../firebase/client";
import Github from "../icons/Github";
import styles from "../styles/Home.module.css";
export default function Home() {
  const [user, setUser] = useState(undefined);

  useEffect(() => {
    onAuthStateChange(setUser);
  }, []);

  const handleClick = () => {
    loginWithGitHub()
      .then((response) => {
        setUser(response);
      })
      .catch((error) => {
        console.error(error);
      });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Terclone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Terclone</h1>
        <h2 className={styles.subtitle}>
          Talk about development about with developers
        </h2>
        <div className={styles.action}>
          {user === null && (
            <Button onClick={handleClick}>
              <Github fill="#fff" height="24" width="24" />
              Login with Gtihub
            </Button>
          )}
          {user && user.avatar && (
            <Avatar image={user.avatar} username={user.username} />
          )}
        </div>
      </main>
    </div>
  );
}
