import Devit from 'components/Devit'
import Layout from 'components/Layout'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import useUser from 'hooks/useUser'
import styles from 'styles/pages/Home.module.css'
import { fetchLatestDevits } from 'firebase/client'
export default function Home() {
  useUser()
  const user = useUser()
  const [timeLine, setTimeline] = useState([])

  useEffect(() => {
    user &&
      fetchLatestDevits().then((doc) => {
        setTimeline(doc)
      })
  }, [])

  return (
    <Layout>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <p className={styles.headerTitle}>Home</p>
      </header>
      <section className={styles.content}>
        {timeLine.map((current) => {
          return (
            <Devit
              avatar={current.avatar}
              createdAt={current.createdAt}
              key={current.id}
              id={current.id}
              content={current.content}
              userName={current.userName}
              userId={current.userId}
            />
          )
        })}
      </section>
      <nav className={styles.nav}>
        <h3>Navigation</h3>
      </nav>
    </Layout>
  )
}
